### ISSUE TITLE
500 error - Undefined index: ref

### ISSUE THREAD

**Issue by nicklasafe** [orphans/git-deploy-laravel#11]
I'm using Github and have things mostly working. The trigger actually pulls the code but it dies sometime after that with this error message:

`Undefined index: ref`

The middle line below from GitDeployController.php is where it chokes:
`
// Get branch this webhook is for
$pushed_branch = explode('/', $postdata['ref']);
$pushed_branch = trim($pushed_branch[2]);
`
Weirdly enough, if I check the payload on my github webhook it looks like this:
`
{
  "ref": "refs/heads/master",
  "before": "2ed33d476e7514eb079fa36bbd1280f3061a7c78",
  "after": "f2115760f1239c74c533c59d4af29f24c9ee85a9",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
...
`
So the ref is definately there. Any ideas? I'm not getting email notifications att his point so would like to solve this.

**Comment by Muffinman** [comment]
Hmm I'm not sure, we've not done extensive testing with Github since we primarily use this package ourselves with Gitlab. That said, the payload information for both is almost identical [[1]](https://developer.github.com/v3/activity/events/types/#pushevent) [[2]](https://docs.gitlab.com/ce/user/project/integrations/webhooks.html).

Would you be able to `var_dump()` the contents of `$postdata` at line 46?

Can you also confirm what PHP version you are using?

**Comment by Muffinman** [comment]
Closing this for now... feel free to re-open if you're still having the problem.
